[chains]
"custom_lobby" = [
  { x = 141, y = 429, delay = 800},
  { x = 1641, y = 356, delay = 800},
  { x = 1773, y = 279, delay = 1500},
]
"move_self_spec" = [
  { x = 1403, y = 260, delay = 50},
  { x = 1128, y = 430, delay = 50},
  { x = 886, y = 850, delay = 50},
  { x = 1415, y = 259, delay = 50},
]
"set_preset" = [
  { x = 1552, y = 237, delay = 50},
  { x = 281, y = 365, delay = 500},
  { x = 489, y = 356, delay = 700},
  { x = 1042, y = 604, delay = 100},
  { x = 1797, y = 1006, delay = 100},
  { x = 1797, y = 1006, delay = 0},
]
